package com.oryno.piggy_ledger.ui

data class CurrencyInfo(val code: String, val name: String, val flag: String, val symbol: String)

val availableCurrencies = listOf(
    CurrencyInfo("USD", "US Dollar", "🇺🇸", "\$"),
    CurrencyInfo("EUR", "Euro", "🇪🇺", "€"),
    CurrencyInfo("GBP", "British Pound", "🇬🇧", "£"),
    CurrencyInfo("JPY", "Japanese Yen", "🇯🇵", "¥"),
    CurrencyInfo("CNY", "Chinese Yuan", "🇨🇳", "CN¥"),
    CurrencyInfo("CAD", "Canadian Dollar", "🇨🇦", "CA\$"),
    CurrencyInfo("AUD", "Australian Dollar", "🇦🇺", "A\$"),
    CurrencyInfo("CHF", "Swiss Franc", "🇨🇭", "CHF"),
    CurrencyInfo("INR", "Indian Rupee", "🇮🇳", "₹"),
    CurrencyInfo("BRL", "Brazilian Real", "🇧🇷", "R\$"),
    CurrencyInfo("RUB", "Russian Ruble", "🇷🇺", "₽"),
    CurrencyInfo("KRW", "South Korean Won", "🇰🇷", "₩"),
    CurrencyInfo("SGD", "Singapore Dollar", "🇸🇬", "S\$"),
    CurrencyInfo("HKD", "Hong Kong Dollar", "🇭🇰", "HK\$"),
    CurrencyInfo("NZD", "New Zealand Dollar", "🇳🇿", "NZ\$"),
    CurrencyInfo("MXN", "Mexican Peso", "🇲🇽", "MX\$"),
    CurrencyInfo("TRY", "Turkish Lira", "🇹🇷", "₺"),
    CurrencyInfo("ZAR", "South African Rand", "🇿🇦", "R"),
    CurrencyInfo("SEK", "Swedish Krona", "🇸🇪", "kr"),
    CurrencyInfo("NOK", "Norwegian Krone", "🇳🇴", "kr"),
    CurrencyInfo("DKK", "Danish Krone", "🇩🇰", "kr"),
    CurrencyInfo("PLN", "Polish Zloty", "🇵🇱", "zł"),
    CurrencyInfo("EGP", "Egyptian Pound", "🇪🇬", "EGP"),
    CurrencyInfo("SAR", "Saudi Riyal", "🇸🇦", "SAR"),
    CurrencyInfo("AED", "UAE Dirham", "🇦🇪", "AED"),
    CurrencyInfo("KWD", "Kuwaiti Dinar", "🇰🇼", "KWD"),
    CurrencyInfo("QAR", "Qatari Riyal", "🇶🇦", "QAR"),
    CurrencyInfo("BHD", "Bahraini Dinar", "🇧🇭", "BHD"),
    CurrencyInfo("OMR", "Omani Rial", "🇴🇲", "OMR"),
    CurrencyInfo("JOD", "Jordanian Dinar", "🇯🇴", "JOD"),
    CurrencyInfo("IQD", "Iraqi Dinar", "🇮🇶", "IQD"),
    CurrencyInfo("LBP", "Lebanese Pound", "🇱🇧", "LBP"),
    CurrencyInfo("SYP", "Syrian Pound", "🇸🇾", "SYP"),
    CurrencyInfo("YER", "Yemeni Rial", "🇾🇪", "YER"),
    CurrencyInfo("MAD", "Moroccan Dirham", "🇲🇦", "MAD"),
    CurrencyInfo("DZD", "Algerian Dinar", "🇩🇿", "DZD"),
    CurrencyInfo("TND", "Tunisian Dinar", "🇹🇳", "TND"),
    CurrencyInfo("LYD", "Libyan Dinar", "🇱🇾", "LYD"),
    CurrencyInfo("SDG", "Sudanese Pound", "🇸🇩", "SDG"),
    CurrencyInfo("MRU", "Mauritanian Ouguiya", "🇲🇷", "MRU"),
    CurrencyInfo("SOS", "Somali Shilling", "🇸🇴", "SOS"),
    CurrencyInfo("DJF", "Djiboutian Franc", "🇩🇯", "Fdj"),
    CurrencyInfo("KMF", "Comorian Franc", "🇰🇲", "CF"),
    CurrencyInfo("ILS", "Israeli Shekel", "🇮🇱", "₪"),
    CurrencyInfo("ARS", "Argentine Peso", "🇦🇷", "\$"),
    CurrencyInfo("BOB", "Bolivian Boliviano", "🇧🇴", "Bs"),
    CurrencyInfo("CLP", "Chilean Peso", "🇨🇱", "\$"),
    CurrencyInfo("COP", "Colombian Peso", "🇨🇴", "\$"),
    CurrencyInfo("CRC", "Costa Rican Colon", "🇨🇷", "₡"),
    CurrencyInfo("DOP", "Dominican Peso", "🇩🇴", "RD\$"),
    CurrencyInfo("GTQ", "Guatemalan Quetzal", "🇬🇹", "Q"),
    CurrencyInfo("HNL", "Honduran Lempira", "🇭🇳", "L"),
    CurrencyInfo("NIO", "Nicaraguan Cordoba", "🇳🇮", "C\$"),
    CurrencyInfo("PAB", "Panamanian Balboa", "🇵🇦", "B/"),
    CurrencyInfo("PEN", "Peruvian Sol", "🇵🇪", "S/"),
    CurrencyInfo("PYG", "Paraguayan Guarani", "🇵🇾", "₲"),
    CurrencyInfo("UYU", "Uruguayan Peso", "🇺🇾", "\$U"),
    CurrencyInfo("VES", "Venezuelan Bolivar", "🇻🇪", "Bs"),
    CurrencyInfo("BBD", "Barbadian Dollar", "🇧🇧", "Bds\$"),
    CurrencyInfo("BSD", "Bahamian Dollar", "🇧🇸", "B\$"),
    CurrencyInfo("BZD", "Belize Dollar", "🇧🇿", "BZ\$"),
    CurrencyInfo("GYD", "Guyanese Dollar", "🇬🇾", "G\$"),
    CurrencyInfo("HTG", "Haitian Gourde", "🇭🇹", "G"),
    CurrencyInfo("JMD", "Jamaican Dollar", "🇯🇲", "J\$"),
    CurrencyInfo("SRD", "Surinamese Dollar", "🇸🇷", "Sr\$"),
    CurrencyInfo("TTD", "Trinidad and Tobago Dollar", "🇹🇹", "TT\$"),
    CurrencyInfo("XCD", "East Caribbean Dollar", "🇦🇬", "EC\$"),
    CurrencyInfo("ALL", "Albanian Lek", "🇦🇱", "L"),
    CurrencyInfo("AMD", "Armenian Dram", "🇦🇲", "֏"),
    CurrencyInfo("AZN", "Azerbaijani Manat", "🇦🇿", "₼"),
    CurrencyInfo("BAM", "Bosnia and Herzegovina Mark", "🇧🇦", "KM"),
    CurrencyInfo("BGN", "Bulgarian Lev", "🇧🇬", "лв"),
    CurrencyInfo("CZK", "Czech Koruna", "🇨🇿", "Kč"),
    CurrencyInfo("GEL", "Georgian Lari", "🇬🇪", "₾"),
    CurrencyInfo("HUF", "Hungarian Forint", "🇭🇺", "Ft"),
    CurrencyInfo("ISK", "Icelandic Krona", "🇮🇸", "kr"),
    CurrencyInfo("MDL", "Moldovan Leu", "🇲🇩", "L"),
    CurrencyInfo("MKD", "Macedonian Denar", "🇲🇰", "ден"),
    CurrencyInfo("RON", "Romanian Leu", "🇷🇴", "lei"),
    CurrencyInfo("RSD", "Serbian Dinar", "🇷🇸", "дин"),
    CurrencyInfo("UAH", "Ukrainian Hryvnia", "🇺🇦", "₴"),
    CurrencyInfo("AFN", "Afghan Afghani", "🇦🇫", "؋"),
    CurrencyInfo("BDT", "Bangladeshi Taka", "🇧🇩", "৳"),
    CurrencyInfo("BND", "Brunei Dollar", "🇧🇳", "B\$"),
    CurrencyInfo("IDR", "Indonesian Rupiah", "🇮🇩", "Rp"),
    CurrencyInfo("KHR", "Cambodian Riel", "🇰🇭", "៛"),
    CurrencyInfo("KGS", "Kyrgyzstani Som", "🇰🇬", "с"),
    CurrencyInfo("KZT", "Kazakhstani Tenge", "🇰🇿", "₸"),
    CurrencyInfo("LAK", "Lao Kip", "🇱🇦", "₭"),
    CurrencyInfo("LKR", "Sri Lankan Rupee", "🇱🇰", "Rs"),
    CurrencyInfo("MMK", "Myanmar Kyat", "🇲🇲", "K"),
    CurrencyInfo("MNT", "Mongolian Tugrik", "🇲🇳", "₮"),
    CurrencyInfo("MOP", "Macanese Pataca", "🇲🇴", "MOP\$"),
    CurrencyInfo("MVR", "Maldivian Rufiyaa", "🇲🇻", "Rf"),
    CurrencyInfo("MYR", "Malaysian Ringgit", "🇲🇾", "RM"),
    CurrencyInfo("NPR", "Nepalese Rupee", "🇳🇵", "रू"),
    CurrencyInfo("PHP", "Philippine Peso", "🇵🇭", "₱"),
    CurrencyInfo("PKR", "Pakistani Rupee", "🇵🇰", "₨"),
    CurrencyInfo("THB", "Thai Baht", "🇹🇭", "฿"),
    CurrencyInfo("TJS", "Tajikistani Somoni", "🇹🇯", "SM"),
    CurrencyInfo("TMT", "Turkmenistani Manat", "🇹🇲", "TMT"),
    CurrencyInfo("TWD", "New Taiwan Dollar", "🇹🇼", "NT\$"),
    CurrencyInfo("UZS", "Uzbekistani Som", "🇺🇿", "soʻm"),
    CurrencyInfo("VND", "Vietnamese Dong", "🇻🇳", "₫"),
    CurrencyInfo("FJD", "Fijian Dollar", "🇫🇯", "FJ\$"),
    CurrencyInfo("PGK", "Papua New Guinean Kina", "🇵🇬", "K"),
    CurrencyInfo("SBD", "Solomon Islands Dollar", "🇸🇧", "SI\$"),
    CurrencyInfo("TOP", "Tongan Paʻanga", "🇹🇴", "T\$"),
    CurrencyInfo("VUV", "Vanuatu Vatu", "🇻🇺", "VT"),
    CurrencyInfo("WST", "Samoan Tala", "🇼🇸", "WS\$"),
    CurrencyInfo("AOA", "Angolan Kwanza", "🇦🇴", "Kz"),
    CurrencyInfo("BIF", "Burundian Franc", "🇧🇮", "FBu"),
    CurrencyInfo("BWP", "Botswana Pula", "🇧🇼", "P"),
    CurrencyInfo("CDF", "Congolese Franc", "🇨🇩", "FC"),
    CurrencyInfo("CVE", "Cape Verdean Escudo", "🇨🇻", "Esc"),
    CurrencyInfo("ETB", "Ethiopian Birr", "🇪🇹", "Br"),
    CurrencyInfo("GHS", "Ghanaian Cedi", "🇬🇭", "GH₵"),
    CurrencyInfo("GMD", "Gambian Dalasi", "🇬🇲", "D"),
    CurrencyInfo("GNF", "Guinean Franc", "🇬🇳", "FG"),
    CurrencyInfo("KES", "Kenyan Shilling", "🇰🇪", "KSh"),
    CurrencyInfo("LRD", "Liberian Dollar", "🇱🇷", "L\$"),
    CurrencyInfo("LSL", "Lesotho Loti", "🇱🇸", "L"),
    CurrencyInfo("MGA", "Malagasy Ariary", "🇲🇬", "Ar"),
    CurrencyInfo("MUR", "Mauritian Rupee", "🇲🇺", "Rs"),
    CurrencyInfo("MWK", "Malawian Kwacha", "🇲🇼", "MK"),
    CurrencyInfo("MZN", "Mozambican Metical", "🇲🇿", "MT"),
    CurrencyInfo("NAD", "Namibian Dollar", "🇳🇦", "N\$"),
    CurrencyInfo("NGN", "Nigerian Naira", "🇳🇬", "₦"),
    CurrencyInfo("RWF", "Rwandan Franc", "🇷🇼", "FRw"),
    CurrencyInfo("SCR", "Seychellois Rupee", "🇸🇨", "SR"),
    CurrencyInfo("SLL", "Sierra Leonean Leone", "🇸🇱", "Le"),
    CurrencyInfo("STN", "Sao Tome and Principe Dobra", "🇸🇹", "Db"),
    CurrencyInfo("SZL", "Swazi Lilangeni", "🇸🇿", "L"),
    CurrencyInfo("TZS", "Tanzanian Shilling", "🇹🇿", "TSh"),
    CurrencyInfo("UGX", "Ugandan Shilling", "🇺🇬", "USh"),
    CurrencyInfo("XAF", "Central African CFA Franc", "🇨🇲", "FCFA"),
    CurrencyInfo("XOF", "West African CFA Franc", "🇸🇳", "CFA"),
    CurrencyInfo("ZMW", "Zambian Kwacha", "🇿🇲", "ZK"),
)

fun getCurrencySymbol(code: String): String {
    return availableCurrencies.find { it.code.equals(code, ignoreCase = true) }?.symbol ?: code
}
